[phases.setup]
nixPkgs = ["dotnet-sdk"]

[variables]
DOTNET_VERSION = "8.0"

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "dotnet LibraryMPT.dll"

